name: noop

on: workflow_dispatch

permissions:
  id-token: write

jobs:
  nonsense:
    name: Release packages
    runs-on: self-hosted
    steps:
      - name: Checkout source
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c # v3


      - name: Sleepy time
        run: |
          node sleep.js

